name: 'Carbon Measurement'
description: 'Read in an infrastructure as code template and then estimate the carbon emissions'
inputs:
  IACType:
    description: 'Type of file for Infrastructure as Code'
    required: true
    default: 'arm'
  IACFile:
    description: 'IAC Filename'
    required: true
    default: 'infra.json'
  ELECTRICITY_MAP_AUTH_TOKEN:
    description: 'Authentication token to access Electricity Map API'
    required: true

outputs:
  grams_carbon_equivalent_per_kwh:
    description: 'Grams of Carbon Equivalent per kWh for the selected location'
  grams_emitted_over_24h:
    description: 'Grams of Carbon Equivalents emitted over 24 hours'
runs:
  using: composite
  steps:
  - name: if IACFileType is already ARM template
    if: inputs.IACType == 'arm'
    run: echo "ARMTemplateFilename=${{inputs.IACFile}}" >> $GITHUB_ENV
    shell: bash

  - name: Set default value for ARMTemplateFilename
    if: inputs.IACType == 'bicep'
    run: echo "ARMTemplateFilename=${GITHUB_RUN_ID}_ARM.json" >> $GITHUB_ENV
    shell: bash    

  - name: Build bicep file
    if: inputs.IACType == 'bicep'
    uses: azure/bicep-build-action@v1.0.0
    with:
      bicepFilePath: ${{ inputs.IACFile }}
      outputFilePath: ${{ env.ARMTemplateFilename }}
      
  - name: Set ELECTRICITY_MAP_AUTH_TOKEN env variable
    run: echo "ELECTRICITY_MAP_AUTH_TOKEN=${{inputs.ELECTRICITY_MAP_AUTH_TOKEN}}" >> $GITHUB_ENV
    shell: bash

  - run: go run ${{ github.action_path }}/carbon_measure.go
    shell: bash
